-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\sigma_delta_fxp_hdl_tc.vhd
-- Created: 2011-08-24 15:40:06
-- 
-- Generated by MATLAB 7.12 and Simulink HDL Coder 2.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sigma_delta_fxp_hdl_tc
-- Source Path: sigma_delta_fxp_hdl_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_1_1   : identical to clk_enable
-- enb_1_512_0 : 512x slower than clk_enable with last phase
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY sigma_delta_fxp_hdl_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_1_1                         :   OUT   std_logic;
        enb_1_512_0                       :   OUT   std_logic
        );
END sigma_delta_fxp_hdl_tc;


ARCHITECTURE rtl OF sigma_delta_fxp_hdl_tc IS

  -- Signals
  SIGNAL count512                         : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL phase_all                        : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;

BEGIN
  Counter512 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      count512 <= to_unsigned(1, 9);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF count512 = to_unsigned(511, 9) THEN
          count512 <= to_unsigned(0, 9);
        ELSE
          count512 <= count512 + 1;
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter512;

  phase_all <= '1' WHEN clk_enable = '1' ELSE '0';

  temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_0 <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  phase_0_tmp <= '1' WHEN count512 = to_unsigned(511, 9) AND clk_enable = '1' ELSE '0';

  enb <=  phase_all AND clk_enable;

  enb_1_1_1 <=  phase_all AND clk_enable;

  enb_1_512_0 <=  phase_0 AND clk_enable;


END rtl;

